python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016apv -i DoubleMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016apv -i DoubleMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016apv -i DoubleElectron -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016apv -i DoubleElectron -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016apv -i ElectronMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016apv -i ElectronMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016postapv -i DoubleMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016postapv -i DoubleMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016postapv -i DoubleElectron -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016postapv -i DoubleElectron -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016postapv -i ElectronMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2016postapv -i ElectronMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2017 -i DoubleMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2017 -i DoubleMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2017 -i DoubleElectron -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2017 -i DoubleElectron -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2017 -i ElectronMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2017 -i ElectronMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2018 -i DoubleMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2018 -i DoubleMuon -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2018 -i DoubleElectron -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2018 -i DoubleElectron -a 3 -x 1 ;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2018 -i ElectronMuon -a 3 -x 0;
python3 ./WorkFlow/main.py -m DrellYanRECO -y 2018 -i ElectronMuon -a 3 -x 1 ;

